version: '3'

services:
  db:
    image: postgres:12.18-bullseye
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    container_name: tech-harbor-database
    volumes:
      - ./postgres:/var/lib/postgresql/data
